var keymap_1 = (function(){
  var watch_keys = [65,83,68,70,32];
  var key_layout = ['a','s','d','f','space'];
  var keycodes = {65:'a',83:'s',68:'d',70:'f',32:'space'};
  var keymap = {
    'space':' ',
    'a':'a',
    's':'b',
    'd':'c',
    'f':'d',
    'a+s':'e',
    's+d':'f',
    'd+f':'g',
    'a+d':'h',
    's+f':'i',
    'a+f':'j',
    'a,s':'k',
    'a,d':'l',
    'a,f':'m',
    's,a':'n',
    's,d':'o',
    's,f':'p',
    'd,a':'q',
    'd,s':'r',
    'd,f':'s',
    'f,a':'t',
    'f,s':'u',
    'f,d':'v',
    'a,s+d':'w',
    'a,s+f':'x',
    'a,d+f':'y',
    's,a+d':'z',
    's,a+f':',',
    's,d+f':';',
    'd,a+s,':'.',
    'd,a+f':'?',
    'd,s+f':'!',
    'f,a+s':'-',
    'f,a+d':'"',
    'f,s+d':"'",
    'a+s,d':'(',
    'a+s,f':')',
    's+d,a':'[',
    's+d,f':']',
    'd+f,a':'{',
    'd+f,s':'}',
    'a,s+d+f':'<',
    's,a+d+f':'>',
    'd,a+s+f':'_',
    'f,a+s+d':'`',
    'a,s,d':'~',
    'a,s,f':'/',
    'a,d,f':'\\',
    's,a,d':'+',
    's,a,f':'-',
    's,d,f':'%',
    'd,a,s':'#',
    'd,a,f':'@',
    'd,s,f':'$',
    'f,a,s':'&',
    'f,a,d':'*',
    'a+s+d+f,space':'0',
    'space+a':'1',
    'space+s':'2',
    'space+d':'3',
    'space+f':'4',
    'space+a+s':'5',
    'space+a+d':'6',
    'space+a+f':'7',
    'space+s+d':'8',
    'space+s+f':'9',
    'a+s+d+f':'<br />',
    'space,a+s+d+f':'backspace'
  };

  return {watch_keys:watch_keys, keycodes:keycodes, map:keymap, key_layout:key_layout};
      

})();
