var keymap_1 = (function(){
  var watch_keys = [65,87,69,70,32];
  var key_layout = ['a','w','e','f','space'];
  var keycodes = {65:'a',87:'w',69:'e',70:'f',32:'space'};
  var keymap = {
    'space':' ',
    'a':'a',
    'w':'b',
    'e':'c',
    'f':'d',
    'a+w':'e',
    'w+e':'f',
    'e+f':'g',
    'a+e':'h',
    'w+f':'i',
    'a+f':'j',
    'a,w':'k',
    'a,e':'l',
    'a,f':'m',
    'w,a':'n',
    'w,e':'o',
    'w,f':'p',
    'e,a':'q',
    'e,w':'r',
    'e,f':'s',
    'f,a':'t',
    'f,w':'u',
    'f,e':'v',
    'a,w+e':'w',
    'a,w+f':'x',
    'a,e+f':'y',
    'w,a+e':'z',
    'w,a+f':',',
    'w,e+f':';',
    'e,a+w,':'.',
    'e,a+f':'?',
    'e,w+f':'!',
    'f,a+w':'-',
    'f,a+e':'"',
    'f,w+e':"'",
    'a+w,e':'(',
    'a+w,f':')',
    'w+e,a':'[',
    'w+e,f':']',
    'e+f,a':'{',
    'e+f,w':'}',
    'a,w+e+f':'<',
    'w,a+e+f':'>',
    'e,a+w+f':'_',
    'f,a+w+e':'`',
    'a,w,e':'~',
    'a,w,f':'/',
    'a,e,f':'\\',
    'w,a,e':'+',
    'w,a,f':'-',
    'w,e,f':'%',
    'e,a,w':'#',
    'e,a,f':'@',
    'e,w,f':'$',
    'f,a,w':'&',
    'f,a,e':'*',
    'a+w+e+f,space':'0',
    'space+a':'1',
    'space+w':'2',
    'space+e':'3',
    'space+f':'4',
    'space+a+w':'5',
    'space+a+e':'6',
    'space+a+f':'7',
    'space+w+e':'8',
    'space+w+f':'9',
    'a+w+e+f':'<br />',
    'space,a+w+e+f':'backspace'
  };

  return {watch_keys:watch_keys, keycodes:keycodes, map:keymap, key_layout:key_layout};
      

})();
